spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gpt-oss:20b
#          model: gpt-oss:20b-cloud
          keep-alive: 1h
          temperature: 0.7
    mcp:
      client:
        enabled: false
####### temporarily moved ConfigurationProperties(prefix = "mcp")
#        sse:
#          connections:
#            profiles-generator-mcp-sse:
#              url: http://localhost:8085
#              sse-endpoint: /sse
#            date-time-mcp-sse:
#              url: http://localhost:8086
#              sse-endpoint: /sse
#            math-tool-mcp-sse:
#              url: http://localhost:8087
#              sse-endpoint: /sse
#            rag-mcp-sse:
#              url: http://localhost:8088
#              sse-endpoint: /sse
####### temporarily moved to McpClientConfig.java

logging:
  level:
    org.springframework.ai: INFO
    io.modelcontextprotocol: INFO

mcp:
  servers:
    - name: "profiles-generator"
      url: "http://localhost:8085"
      endpoint: "/sse"
    - name: "date-time"
      url: "http://localhost:8086"
      endpoint: "/sse"
    - name: "math-tool"
      url: "http://localhost:8087"
      endpoint: "/sse"
    - name: "rag"
      url: "http://localhost:8088"
      endpoint: "/sse"
